apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-react-app.fullname" . }}-config
  labels:
    {{- include "my-react-app.labels" . | nindent 4 }}
data:
  config.js: |
    window.env = {
      envName: "{{ .Values.envName | default "DEVELOPMENT" }}"
    };