replicaCount: 1
autoscaling:
  enabled: false

image:
  repository: vincentmsx/my-react-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""
  automount: true # AJOUTE CELA pour ton template serviceaccount.yaml