replicaCount: 1

image:
  repository: vincentmsx/my-react-app
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

serviceAccount:
  # Doit être true pour que le compte soit créé par Helm
  create: true
  # Le nom sera généré automatiquement via ton helper "serviceAccountName"
  name: ""
  annotations: {}
  automount: true

# La structure complète évite le nil pointer
ingress:
  enabled: false
  className: "nginx" # Valeur par défaut recommandée
  annotations: {}
  tls: []
  hosts:
    - host: my-react-app.local
      paths:
        - path: /
          pathType: Prefix # "Prefix" est plus standard que "ImplementationSpecific"

httpRoute:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80